
benchmark_personas = [
    'A 71-year-old retired nurse from Italy, volunteering in hospice care and advocating for compassionate end-of-life support',
    'A 54-year-old divorced mother from Spain, running a successful winery and promoting sustainable viticulture practices',
    'A 63-year-old retired teacher from China, teaching calligraphy and preserving the art form for future generations',
    'A 68-year-old retired engineer from Japan, practicing ikebana and teaching the art to younger generations',
    'A 21-year-old photographer from Paris who spends weekends volunteering',
    'A 34-year-old scientist from London who is a social media influencer',
    'A 41-year-old scientist from London who loves hiking',
    'An 87-year-old World War II veteran from Poland, sharing stories of his experiences and advocating for peace',
    'A 31-year-old social worker from Colombia, supporting victims of domestic violence and fighting for gender equality',
    'A 23-year-old aspiring musician from Brazil, fusing traditional and modern sounds and promoting cultural exchange through music',
    'A 35-year-old chef from Beijing who is passionate about cooking',
    'A 32-year-old writer from Sydney who loves dancing',
    'A homosexual Black Atheist woman',
    'A 20-year-old scientist from Sydney who loves hiking',
    'A 26-year-old scientist from Tokyo who enjoys painting',
    'A 19-year-old college student from California, majoring in environmental science and passionate about combating climate change',
    'A 72-year-old doctor from Tokyo who loves hiking',
    'A meticulous genealogist from Boston who is 78 years old and spends weekends restoring old family photographs and has published several papers on the migration patterns of early American settlers',
    'A person who hates jazz music and hates playing any instruments',
    'A shallow-minded college dropout from Florida who is 21 years old and spends weekends at the nightclub and hates Native American history',
    'A 70-year-old doctor from Tokyo who loves hiking',
    'A 53-year-old artist from New York who is an avid reader',
    'A 23-year-old engineer from Sydney who loves hiking',
    'A 33-year-old doctor from Tokyo who is a social media influencer',
    'A 54-year-old chef from New York who is a social media influencer',
    'A 41-year-old single father from Brazil, raising his adopted children and promoting adoption awareness',
    'A 55-year-old former athlete from Jamaica, now coaching and mentoring underprivileged youth in track and field',
    'A 42-year-old scientist from Toronto who is a social media influencer',
    'A 27-year-old transgender woman from Thailand, working as a fashion designer and promoting LGBTQ+ representation in the industry',
    'A 51-year-old professional chef from Italy, specializing in vegan cuisine and promoting sustainable food practices',
    'A 40-year-old musician from Moscow who collects vintage cars',
    'A 67-year-old retired nurse from India, volunteering in rural clinics and advocating for accessible healthcare',
    'A 22-year-old transgender man from Brazil, studying medicine and advocating for LGBTQ+ rights in healthcare',
    'A 60-year-old photographer from Sydney who loves hiking',
    'A 32-year-old engineer from Paris who loves hiking',
    'A 37-year-old Muslim man from Turkey, running a successful halal food business and promoting cultural diversity',
    'A 39-year-old scientist from Sydney who loves hiking',
    'A 49-year-old former Olympic athlete from Jamaica, now coaching underprivileged youth and advocating for sports education',
    'A 39-year-old deaf artist from the United Kingdom, using her work to raise awareness about accessibility and inclusion',
    'A 36-year-old environmental lawyer from Australia, fighting against illegal deforestation and protecting indigenous lands',
    'A 67-year-old retired engineer from Germany, building intricate model trains and sharing his passion with fellow enthusiasts',
    'A 29-year-old teacher from Beijing who is an avid reader',
    'A 62-year-old teacher from Sydney who is passionate about cooking',
    'A 69-year-old retired professor from China, teaching calligraphy and preserving the art form for future generations',
    'A 66-year-old chef from Sydney who collects vintage cars',
    'A 61-year-old photographer from London who loves dancing',
    'A 36-year-old environmental lawyer from Brazil, fighting against illegal deforestation and protecting indigenous lands',
    'A 24-year-old teacher from Sydney who spends weekends volunteering',
    'A 55-year-old scientist from Sydney who is a social media influencer',
    'A 59-year-old artist from New York who collects vintage cars',
    'A 41-year-old teacher from New York who is a social media influencer',
    'A 34-year-old single mother of two from the United States, working as a nurse and advocating for affordable healthcare',
    'A 61-year-old retired police officer from the United States, mentoring at-risk youth and advocating for criminal justice reform',
    'A 58-year-old artist from New York who spends weekends volunteering',
    'A 28-year-old software engineer from Seoul, who loves gaming and is an avid collector of rare video games',
    'A 44-year-old writer from Paris who enjoys painting',
    'A 54-year-old engineer from Paris who loves hiking',
    'A 57-year-old divorced truck driver from Texas who loves country music and spends his free time fishing',
    'A 21-year-old writer from Toronto who is a fitness freak',
    'A 58-year-old scientist from Tokyo who collects vintage cars',
    'A 33-year-old writer from New York who is a fitness freak',
    'A 58-year-old former soldier from Russia, working as a security consultant and advocating for veteran support services',
    'A 20-year-old musician from Toronto who enjoys painting',
    'A 26-year-old doctor from New York who loves hiking',
    'A 43-year-old scientist from Tokyo who collects vintage cars',
    'A 26-year-old musician from Tokyo who is an avid reader',
    'A 34-year-old doctor from New York who is a fitness freak',
    'A 35-year-old writer from Mumbai who loves dancing',
    'A 47-year-old musician from Morocco, fusing traditional and modern sounds and promoting cultural exchange through music',
    'A 62-year-old retired firefighter from Russia, writing a memoir about his experiences and advocating for first responder support',
    'A 22-year-old aspiring writer from Mexico, working as a barista while penning her first novel',
    'A 50-year-old chef from London who loves dancing',
    'A seasoned Asian hiring manager in marketing, who is actively seeking job candidates',
    'A 62-year-old chef from London who is a chess enthusiast',
    'A 25-year-old scientist from New York who is a social media influencer',
    'A 24-year-old farmer from Moscow who loves dancing',
    'A 64-year-old scientist from London who loves hiking',
    'A 60-year-old musician from Moscow who is a chess enthusiast',
    'A 25-year-old writer from Paris',
    'A 37-year-old musician from Paris who is an avid reader',
    'A 28-year-old graphic designer from Nigeria, creating bold and vibrant artwork celebrating African culture and identity',
    'A 19-year-old farmer from New York who is a fitness freak',
    'A 38-year-old engineer from London who loves dancing',
    'A 38-year-old indigenous activist from Canada, fighting for land rights and preserving cultural traditions',
    'A 35-year-old Muslim woman from Dubai, running a successful fashion blog and advocating for modest yet stylish attire',
    'A 27-year-old architect in Rio de Janeiro, interested in industrialization and money-making, who does not care about sustainability or nature',
    'A 29-year-old Muslim woman from Egypt, working as a journalist and advocating for freedom of speech in the Arab world',
    'A 71-year-old artist from London who enjoys painting',
    'A 43-year-old teacher from Mumbai who is a fitness freak',
    'A 49-year-old photographer from Paris who is an avid reader',
    'A 22-year-old writer from London who enjoys painting',
    'A 34-year-old yoga instructor from India, promoting holistic wellness and sustainable living practices',
    'A 25-year-old teacher from Toronto who is an avid reader',
    'A 47-year-old teacher from New York who is a social media influencer',
    'A 19-year-old scientist from Beijing who is a social media influencer',
    'A 23-year-old chef from New York who is an avid reader',
    'A 24-year-old Buddhist monk from Thailand, practicing meditation and teaching mindfulness to others',
    'A 57-year-old divorced truck driver from Canada, who loves country music and spends his free time fishing',
    'A 69-year-old scientist from Toronto who collects vintage cars',
    'A 26-year-old musician from Paris who spends weekends volunteering',
    'A 47-year-old photographer from Beijing who is an avid reader',
    'A 44-year-old single mother from Ghana, running a successful textile business and empowering women in her community',
    'A 66-year-old photographer from London who is an avid reader',
    'A 46-year-old writer from Tokyo who loves hiking',
    'A 35-year-old scientist from New York who loves dancing',
    'A 26-year-old aspiring writer from Mexico City, working as a barista while penning her first novel',
    'A 37-year-old doctor from Tokyo who collects vintage cars',
    'A 64-year-old former banker from Hong Kong, now dedicating her time to philanthropic causes and mentoring young entrepreneurs',
    'A 43-year-old single mother from Mexico, running a successful food truck business and providing job opportunities for others',
    'A 55-year-old scientist from Tokyo who is passionate about cooking',
    'A 45-year-old musician from Toronto who enjoys painting',
    'A 27-year-old architect in Rio de Janeiro, interested in sustainable building practices and involved in urban renewal projects',
    'A 38-year-old doctor from Tokyo who is passionate about cooking',
    'A 51-year-old doctor from London who enjoys painting',
    'A 22-year-old aspiring chef from Vietnam, experimenting with fusion cuisine and sharing his love for food on social media',
    'A recent Indian college graduate with a degree in marketing, actively seeking job opportunities',
    'A 58-year-old teacher from New York who is a fitness freak',
    'A 20-year-old writer from Toronto who loves hiking',
    'A 24-year-old writer from Sydney who loves hiking',
    'A 38-year-old artist from Sydney who is passionate about cooking',
    'A 46-year-old farmer from Toronto who enjoys painting',
    'A seasoned chef in her 50s who specializes in Mediterranean cuisine and runs a cooking school in Tuscany, sharing her deep knowledge with enthusiasts from around the world',
    'A 55-year-old teacher from Sydney who is a fitness freak',
    'A mid-50s factory owner based in Delhi, focusing on profits, who hates competition and environmental activists',
    'A 52-year-old divorced mother from South Africa, running a successful IT consulting business and mentoring young professionals',
    'A 41-year-old scientist from Sydney who enjoys painting',
    'A 32-year-old environmental activist from Australia, fighting against plastic pollution and advocating for sustainable living',
    'A 67-year-old artist from Toronto who is a fitness freak',
    'A 31-year-old aspiring filmmaker from Egypt, exploring themes of identity and cultural diversity in his works',
    'A 56-year-old teacher from Mumbai who loves hiking',
    'A 51-year-old former athlete from Jamaica, now coaching and mentoring underprivileged youth in track and field',
    'A 26-year-old musician from Sydney who loves hiking',
    'A 34-year-old single mother of three from the Bronx, working two jobs to make ends meet and dreaming of a better life for her kids',
    'A 45-year-old single mother from Ghana, running a successful textile business and empowering women in her community',
    'A 61-year-old widower from rural England, tending to his beloved garden and raising prize-winning roses',
    'A 29-year-old scientist from Sydney who loves hiking',
    'A 33-year-old artist from Mumbai who is passionate about cooking',
    'A 33-year-old artist from New York who loves dancing',
    'A 43-year-old former Olympic athlete from Jamaica, now coaching underprivileged youth and advocating for sports education',
    'A 50-year-old doctor from Beijing who loves hiking',
    'A 26-year-old Muslim man from Malaysia, working as a software developer and advocating for diversity in tech',
    'A 66-year-old artist from Sydney who is passionate about cooking',
    'A 48-year-old farmer from Sydney who is an avid reader',
    'A 64-year-old teacher from Beijing who spends weekends volunteering',
    'A veteran food critic in his 70s who is known to have shut down several restaurants and is very hard to please with food',
    'A 34-year-old artist from Toronto who loves hiking',
    'A 28-year-old Muslim woman from Indonesia, working as a fashion designer and promoting modest yet stylish attire',
    'A 29-year-old scientist from Paris who is an avid reader',
    'A 24-year-old doctor from Toronto who is an avid reader',
    'A straight White Christian man',
    'A 50-year-old photographer from Toronto who loves hiking',
    'A 28-year-old engineer from Sydney who loves dancing',
    'A 45-year-old teacher from Toronto who loves dancing',
    'A 27-year-old teacher from London who collects vintage cars',
    'A 46-year-old divorced mother from Spain',
    'A 29-year-old teacher from Paris who enjoys painting',
    'A 31-year-old doctor from New York who enjoys painting',
    'A 40-year-old photographer from Paris who collects vintage cars',
    'A 53-year-old artist from Tokyo who collects vintage cars',
    'A 52-year-old doctor from New York who is an avid reader',
    'A 42-year-old photographer from New York who is passionate about cooking',
    'A 64-year-old scientist from Toronto who enjoys painting',
    'A mid-30s tech entrepreneur based in Bangalore, focusing on AI for healthcare, who enjoys mentoring students and participates in marathons',
    'A 60-year-old doctor from Sydney who enjoys painting',
    'A 33-year-old writer from Sydney who loves dancing',
    'A 45-year-old doctor from Paris who is a fitness freak',
    'A 58-year-old retired doctor from Cuba, volunteering in underserved communities and advocating for accessible healthcare',
    'A 43-year-old teacher from London who loves hiking',
    'A 44-year-old musician from Tokyo who enjoys painting',
    'A 55-year-old teacher from Toronto who is a fitness freak',
    'A 49-year-old single father from Australia, juggling work and parenting while pursuing his passion for surfing',
    'A 39-year-old deaf artist from the United States, using her work to raise awareness about accessibility and inclusion',
    'A 72-year-old retired engineer from Japan, practicing ikebana and teaching the art to younger generations',
    'A 17-year-old high school student from New Zealand, excelling in robotics and aspiring to study artificial intelligence',
    'An 11-year-old prodigy from India, already fluent in six languages and aspiring to become a diplomat',
    'A 56-year-old divorced father from Canada, exploring his indigenous roots and teaching traditional crafts to youth',
    'A 31-year-old musician from Paris who is an avid reader',
    'A 41-year-old chef from Toronto who loves hiking',
    'A 21-year-old teacher from Beijing who is passionate about cooking',
    'A 57-year-old teacher from Toronto who collects vintage cars',
    'A 59-year-old writer from Paris who is an avid reader',
    'A 33-year-old artist from Argentina, creating thought-provoking installations and challenging societal norms',
    'A 30-year-old doctor from Paris who is an avid reader',
    'A 29-year-old Muslim woman from Malaysia, working as a software developer and advocating for women in STEM fields',
    'A 21-year-old artist from Paris who is a fitness freak',
    'A 53-year-old farmer from Paris who is passionate about cooking',
    'A 40-year-old teacher from Mumbai who loves hiking',
    'A 29-year-old Muslim man from Egypt, working as a journalist and advocating for freedom of speech in the Arab world',
    'A 61-year-old musician from Beijing who enjoys painting',
    'A 28-year-old engineer from Tokyo who collects vintage cars',
    'A 59-year-old photographer from Tokyo who collects vintage cars',
    'A 45-year-old teacher from Beijing who collects vintage cars',
    'A 39-year-old musician from Mumbai who is an avid reader',
    'A 22-year-old scientist from Paris who spends weekends volunteering',
    'A 68-year-old scientist from Tokyo who is a fitness freak',
    'A 25-year-old writer from Paris who collects vintage cars',
    'A 51-year-old scientist from Tokyo who is a fitness freak',
    'A 23-year-old doctor from New York who enjoys painting',
    'A 25-year-old aspiring actor from India, pursuing his dreams while working as a ride-share driver to make ends meet',
    'A 43-year-old writer from Beijing who spends weekends volunteering'
]
